### ISSUE TITLE
Restructure main navigation menu

### ISSUE THREAD

**Issue by ftarulla** [crystal-lang/crystal-website#284]
# One issue (or Menu) to rule them all 🧙‍♂️
This issue is an _umbrella issue_, and it can be used as a foreword and index for some changes for the site's menu (and to start the discussion)

They are not _big_ changes but can make a difference when starting to navigate the site for the first time (trying to know/learn about Crystal)

The changes are the result of navigating Crystal's site and some other programming languages' sites (for example Ruby, Rust, Dart, Go) while having in mind the following:
- Easy navigation from `Home` to a page (for example `Blog`) and back to `Home`
- Navigation flow from newcomers' pov (both advanced and beginners)
- Can the `Menu` be simpler? (ie can we remove some item without losing the essence)

Here is the list of issue for some specific changes:

- #276 Remove `Home` from menu
- #278 Remove `GitHub` from menu
- #280 Remove `Forum` from menu
- #282 Remove `Conference` from menu

## Also in this issue ...

... there is a description of Adding `Install`, `Learn` and `Try Online`.  These options are buttons on the `main` page but when navigating to other pages are not accessible any more, making it hard for (not only) newcomers to access this important options.

This new options shouldn't be necessary in the `main` page because we have the 3 buttons so it would be good to have a "dynamic" menu.

This issue would be also a good place to rearrange the items making more newcomers friendly. For example we could sort the menu like this:

Install - Learn - Try online - Docs - Tools - Community - Blog - Team - Sponsors

Read this menu like this:
- The first 3 items `Install`, `Learn` and `Try online` are focused on adopting the language
- The next one `Docs` is focused on mastering the language
- Then we focus on building a community (`Community` and `Blog`)
- At the end we have the `team` behind Crystal and the `sponsors` backing it up 

Also notice a **new item** `Tools` linking to (the external) https://github.com/crystal-lang-tools. This element is more focused on adopting the language and it could be placed before the `Docs` item but then, when in the `main` page, it would be the first item in the menu linking to an external site, meaning that the first element on the menu (in the `main` page) navigates away from the site (and that would be a not so good user experience)

Check the PoC in #285

**Comment by straight-shoota** [comment]
I think it's important to keep the number of navigation items low and focused. I'd rather consider a nested navigation structure than having a main navigation with too many entries. When you compare the main navigation of the mentioned websites of other languages, they usually have 6 or 7 entries. This proposal would end up with 9.

I'd like to consolidate, see what's really necessary, and what can be made accessible in a different way.
It's not just about plain numbers, but what makes sense for guiding the user (and not overwhelming them).

For example, *Install* and *Learn* are very similar in scope and purpose. To substantiate that: The first link on the *Getting started* page (where *Learn* leads) points to *Install*. And every *Install* leads to *Learn*/*Getting started* as a next step.
The *Getting started* guide (again, *Learn*) is also a part of the *Docs* section. That makes another navigation item closely related.

I'm wondering if moving the home page's action buttons (*Install*, *Learn*, *Try online*) to the navigation menu is such a good idea overall. They make sense to guide a reader to good starting points when they land on the home page. But I feel there's not so much value in having links directly and easily available on *every* page.

Anyway, I think  #286 should help us with the overall picture and deriving effective means of navigation.

**Comment by straight-shoota** [comment]
An important piece for the page-wide navigation is how to integrate pages that are *not* incorporated into the main navigation menu. The landing pages of each section serve as navigation hub for its contents. But on those subpages there is no information about the navigation context.

1. The content of this website has a hierarchical structure (cf. #286), with most of the pages belonging to the *Community* or *Docs* section. We might consider a hierarchical navigation menu to represent the subpages in those sections. Example:
  ![grafik](https://user-images.githubusercontent.com/466378/157867796-275ba4ad-8a14-493b-b441-f2e230253f52.png)
  However, many of the resources, especially in the *Docs* section are actually external. Thus we can incorporate outgoing links into the navigation, but there typically won't be returning links or even a representation of this navigation structure on those external pages.

2. An alternative (or addition) to that could be breadcrumb navigation. This only serves the purpose of indicating the location of the current page in the navigation structure and accessing higher ranking pages. It does not easily enable navigation between different pages in the same section as a hierachical menu would. But I'm not sure that's actually of much importance because the individual pages in a section are typically not that closely related, so there's not much need for cross navigation.

**Comment by straight-shoota** [comment]
Resolved by #416
