### ISSUE TITLE
Relaunch: the images in success stories are too wide

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal-website#662]
in the article the images are spawning overflowing the text area (noted with 661, but it's unrelated):

<img width="1534" alt="image" src="https://github.com/crystal-lang/crystal-website/assets/5183634/45efde2a-48c2-4114-bf8d-e6e9ff1fe3c2">

**Comment by straight-shoota** [comment]
Yes, header images span the full width of the body area. That's the same as the footer, for example.
This is intentional, but the entire thing is also not fully worked through. So limiting to the width of the text paragraphs would be fine as well. We could also consider something entirely different. For example put the header image in the background with overlaying title, like on the manas blog.
